<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-BPKQ36I" name="com.training.complex.tests.TC12_064AddMultipleCategory" tests="1" failures="0" timestamp="2019-12-04T11:58:12 IST" time="0.818" errors="1">
  <testcase name="addCatagory" time="0.818" classname="com.training.complex.tests.TC12_064AddMultipleCategory">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
[public void com.training.complex.tests.TC12_064AddMultipleCategory.addCatagory(java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: addCatagory([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) mona,(java.lang.String) Patil,(java.lang.String) mona333@gmail.com,(java.lang.String) 7.654356789E9,(java.lang.String) wagholi,(java.lang.String) pune,(java.lang.String) 412207.0,(java.lang.String) India,(java.lang.String) Maharashtra,(java.lang.String) nov22nov,(java.lang.String) nov22nov]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
[public void com.training.complex.tests.TC12_064AddMultipleCategory.addCatagory(java.lang.String,java.lang.String,java.lang.String,java.lang.String)] has no parameters defined but was found to be using a data provider (either explicitly specified or inherited from class level annotation).
Data provider mismatch
Method: addCatagory([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=3, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) mona,(java.lang.String) Patil,(java.lang.String) mona333@gmail.com,(java.lang.String) 7.654356789E9,(java.lang.String) wagholi,(java.lang.String) pune,(java.lang.String) 412207.0,(java.lang.String) India,(java.lang.String) Maharashtra,(java.lang.String) nov22nov,(java.lang.String) nov22nov]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:43)
at org.testng.internal.Parameters.injectParameters(Parameters.java:925)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:34)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- addCatagory -->
</testsuite> <!-- com.training.complex.tests.TC12_064AddMultipleCategory -->
